services:
  - type: web
    name: kpmg-lms-pipeline
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 --timeout 120 -k uvicorn.workers.UvicornWorker api.app:app
    envVars:
      - key: GRADIO_ANALYTICS_ENABLED
        value: "False"
      - key: MPLCONFIGDIR
        value: "/tmp/matplotlib"
      - key: N_JOBS
        value: "1"
